export const tourSteps = [
  {
    partKey: 'intro',
    partLabel: 'Every Part Matters',
    teamName: 'The Power of Working Together',
    teamDesc: 'A car is more than the sum of its parts. The engine provides power. The steering provides direction. The fuel keeps it going. But none of these matter in isolation. It is only when every component operates at its best — and in concert with every other — that the machine performs the way it was designed to.\n\nThe same is true for the Finance Department. Each function on this team is a precision-engineered part of something larger. When one part fails, the whole system feels it. When every part is firing, the department moves with purpose, speed, and confidence.\n\nLet\'s look under the hood.',
    failureText: '',
  },
  {
    partKey: 'engine',
    partLabel: 'The Engine',
    teamName: 'Budget & Financial Planning',
    teamDesc: 'Every dollar JCPRD deploys starts here. Budget & Financial Planning converts a mix of property tax, enterprise revenue, and fee income into the operating plan that powers every division — balancing public accountability with the ambition to serve millions of visits a year.',
    failureText: 'Without Budget & Financial Planning, the district has resources but no roadmap. Without this piece, spending outpaces revenue, and the engine seizes.',
  },
  {
    partKey: 'fuel',
    partLabel: 'The Fuel System',
    teamName: 'Revenue & Fee Management',
    teamDesc: 'JCPRD funds nearly half of its budget from non-tax sources such as program fees, facility rentals, and other revenue sources. Revenue & Fee Management keeps the tank full so operations can continue in a positive direction.',
    failureText: 'Without Revenue & Fee Management, the fuel line runs dry.',
  },
  {
    partKey: 'transmission',
    partLabel: 'The Transmission',
    teamName: 'Accounts Payable & Procurement',
    teamDesc: 'Every vendor payment, every contract, every purchase order — AP & Procurement transfers the budget\'s power to the people and partners who deliver results.',
    failureText: 'Without AP & Procurement, the budget exists on paper but never reaches the field. Vendors go unpaid, projects freeze, and the district\'s power never makes it past the gearbox.',
  },
  {
    partKey: 'wheels',
    partLabel: 'The Wheels',
    teamName: 'Payroll',
    teamDesc: 'All of JCPRD\'s full-time and seasonal employees depend on Payroll to keep moving. Every pay cycle— Payroll is where the district\'s financial commitments meet the people who make it all happen.',
    failureText: 'Without Payroll, the entire workforce feels it — immediately. Morale drops, trust erodes, and every division grinds to a halt because the people who do the work aren\'t taken care of.',
  },
  {
    partKey: 'body',
    partLabel: 'The Body & Frame',
    teamName: 'Grants and Capital Projects',
    teamDesc: 'The Mid-America West Sports Complex project, the Theatre in the Park renovation and the Administration Building remodel are just a few of the many projects JCPRD has completed. Finance staff that handle Grant and capital asset management provide the structural integrity that holds JCPRD\'s long-term future together.',
    failureText: 'Without Grants and Capital Projects, the district has no structural integrity. Short-term operations survive, but long-term investments collapse.',
  },
  {
    partKey: 'steering',
    partLabel: 'The Steering',
    teamName: 'Financial Reporting',
    teamDesc: 'The financial statements tell leadership exactly where the district stands. Reporting & Compliance steers every strategic decision with facts — turning raw numbers into the clarity that keeps JCPRD on course.',
    failureText: 'Without Financial Reporting, leadership is driving blind and there is no way to know if the district is gaining ground or drifting off course.',
  },
];
