export const tourSteps = [
  {
    partKey: 'intro',
    partLabel: 'Every Part Matters',
    teamName: 'The Power of Working Together',
    teamDesc: 'A car is more than the sum of its parts. The engine provides power. The steering provides direction. The fuel keeps it going. But none of these matter in isolation. It is only when every component operates at its best — and in concert with every other — that the machine performs the way it was designed to.\n\nThe same is true for JCPRD Finance. Each function on this team is a precision-engineered part of something larger. When one part fails, the whole system feels it. When every part is firing, the district moves with purpose, speed, and confidence.\n\nLet\'s look under the hood.',
    failureText: '',
  },
  {
    partKey: 'engine',
    partLabel: 'The Engine',
    teamName: 'Budget & Financial Planning',
    teamDesc: 'Every dollar JCPRD deploys starts here. Budget & Financial Planning converts a $45 million mix of property tax, enterprise revenue, and fee income into the operating plan that powers every division — balancing public accountability with the ambition to serve 2.7 million visits a year.',
    failureText: 'Without Budget & Financial Planning, the district has resources but no roadmap. Divisions compete instead of collaborate, spending outpaces revenue, and the engine seizes.',
  },
  {
    partKey: 'wheels',
    partLabel: 'The Wheels',
    teamName: 'Payroll',
    teamDesc: 'Over 500 full-time and seasonal employees depend on Payroll to keep moving. Every pay cycle, every benefit deduction, every new-hire onboarding — Payroll is where the district\'s financial commitments meet the people who make it all happen.',
    failureText: 'Without Payroll, the entire workforce feels it — immediately. Morale drops, trust erodes, and every division grinds to a halt because the people who do the work aren\'t taken care of.',
  },
  {
    partKey: 'steering',
    partLabel: 'The Steering',
    teamName: 'Financial Reporting & Compliance',
    teamDesc: 'GAAP, GASB, annual audits, and the financial statements that tell leadership exactly where the district stands. Reporting & Compliance steers every strategic decision with facts — turning raw numbers into the clarity that keeps JCPRD on course.',
    failureText: 'Without Financial Reporting, leadership is driving blind. No audit trail, no compliance, no way to know if the district is gaining ground or drifting off course.',
  },
  {
    partKey: 'fuel',
    partLabel: 'The Fuel System',
    teamName: 'Revenue & Fee Management',
    teamDesc: 'JCPRD funds nearly 50% of its budget from non-tax sources — double the national average. Program fees, facility rentals, golf revenue, scholarship adjustments — Revenue & Fee Management keeps the tank full so the district never has to choose between ambition and sustainability.',
    failureText: 'Without Revenue & Fee Management, the fuel line runs dry. Tax levy alone can\'t sustain the mission, programs lose funding, and the district stalls.',
  },
  {
    partKey: 'transmission',
    partLabel: 'The Transmission',
    teamName: 'Accounts Payable & Procurement',
    teamDesc: 'Every vendor payment, every contract, every purchase order — AP & Procurement transfers the budget\'s power to the people and partners who deliver results. From trail materials to program supplies, this team makes sure resources reach the road.',
    failureText: 'Without AP & Procurement, the budget exists on paper but never reaches the field. Vendors go unpaid, projects freeze, and the district\'s power never makes it past the gearbox.',
  },
  {
    partKey: 'body',
    partLabel: 'The Body & Frame',
    teamName: 'Grants, Capital Projects & Risk',
    teamDesc: 'The $9 million Camp Branch Park build. The Theatre in the Park renovation. Heritage Park Lake dredging. Grant compliance, capital improvement planning, insurance, and risk management — this team is the structural integrity that holds JCPRD\'s long-term future together.',
    failureText: 'Without Grants, Capital & Risk, the district has no structural integrity. Short-term operations survive, but long-term investments collapse and one unmanaged risk can crack the whole frame.',
  },
];
